# Generated by Django 5.0.6 on 2024-06-18 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.doctorschedule'),
        ),
    ]
